apiVersion: batch/v1
kind: Job
metadata:
  generateName: smart-parking-db-init-
  namespace: smart-parking

spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 300

  template:
    metadata:
      labels:
        app: smart-parking-db-init

    spec:
      restartPolicy: Never

      containers:
        - name: db-init
          image: smartparking-backend:latest
          imagePullPolicy: IfNotPresent

          command:
            - node
            - scripts/init-local-db.js

          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: smart-parking-config
                  key: AWS_REGION

            - name: DYNAMODB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: smart-parking-config
                  key: DYNAMODB_ENDPOINT

            - name: AWS_ACCESS_KEY_ID
              value: "local"

            - name: AWS_SECRET_ACCESS_KEY
              value: "local"