apiVersion: v1
kind: Service
metadata:
  name: smart-parking-dynamodb
  namespace: smart-parking
spec:
  selector:
    app: smart-parking-dynamodb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP