apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-parking-dynamodb
  namespace: smart-parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-parking-dynamodb
  template:
    metadata:
      labels:
        app: smart-parking-dynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          command:
            - java
            - -jar
            - DynamoDBLocal.jar
            - -sharedDb
            - -inMemory