apiVersion: v1
kind: Service
metadata:
  name: smart-parking-frontend
  namespace: smart-parking
spec:
  selector:
    app: smart-parking-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort