apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smart-parking-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - smart-parking
  selector:
    matchLabels:
      app: smart-parking-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s